# Generated by Django 5.0.1 on 2024-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tempo_servico',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
