# Generated by Django 5.0.1 on 2024-01-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao_modelo_ia',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
