# Generated by Django 5.0.1 on 2024-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_servico_tempo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(default='', max_length=200, null=True),
        ),
    ]
