# Generated by Django 5.0.1 on 2024-01-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_remove_evento_descricao_remove_evento_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.cliente'),
        ),
    ]
