# Generated by Django 5.0.1 on 2024-01-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='data_final',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='data_inicial',
            field=models.DateField(null=True),
        ),
    ]
