# Generated by Django 5.0.1 on 2024-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_configuracao_data_final_configuracao_data_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='horario_final_sabado',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='horario_inicial_sabado',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='trabalha_fim_semana',
            field=models.BooleanField(default=False),
        ),
    ]
