# Generated by Django 5.0.1 on 2024-02-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0014_remove_grupo_group_grupo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='usuario',
        ),
    ]
