# Generated by Django 5.0.1 on 2024-02-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0015_remove_configuracao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='trabalho_domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='trabalho_sabado',
            field=models.BooleanField(default=False),
        ),
    ]
