# Generated by Django 5.0.1 on 2024-02-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0016_configuracao_trabalho_domingo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='horario_final_almoco',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='horario_inicial_almoco',
            field=models.TimeField(null=True),
        ),
    ]
