# Generated by Django 5.0.1 on 2024-02-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0017_configuracao_horario_final_almoco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='horario_final_almoco',
            field=models.TimeField(default='14:00', null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='horario_inicial_almoco',
            field=models.TimeField(default='12:00', null=True),
        ),
    ]
