# Generated by Django 5.0.1 on 2024-02-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0018_alter_configuracao_horario_final_almoco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='url_image',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='identificador_whatsapp_business',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
