# Generated by Django 5.0.1 on 2024-02-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0019_profissional_url_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='id_imagem',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
