# Generated by Django 5.0.1 on 2024-02-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0020_profissional_id_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
