# Generated by Django 5.0.1 on 2024-02-14 18:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0021_profissional_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='cor_primaria_tema',
            field=colorfield.fields.ColorField(blank=True, default='#EF5350', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
