# Generated by Django 5.0.1 on 2024-02-14 19:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0022_configuracao_cor_primaria_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='cor_secundaria_tema',
            field=colorfield.fields.ColorField(blank=True, default='#EF9A9A', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
